[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
    robtillaart/INA226
    bblanchon/ArduinoJson@^7
    knolleary/PubSubClient
build_flags = 
    -D BOARD_HAS_PSRAM

[env:native]
platform = native
framework = arduino
lib_deps = 
    fabiobatsilva/ArduinoFake
test_ignore = 
    test_wifi
    test_mqtt
build_flags = 
    -D ARDUINO_ARCH_ESP32
    -D ARDUINO=20000
    -D ARDUINO_ARCH_ESP32S3