[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
build_flags = -D BOARD_HAS_PSRAM
lib_deps =
    robtillaart/INA226
    bblanchon/ArduinoJson
    knolleary/PubSubClient

[env:native]
platform = native
test_ignore = test_wifi, test_mqtt
build_flags =
    -std=gnu++11
    -Wno-missing-template-arg-list-after-template-kw
lib_deps =
    fabiobatsilva/ArduinoFake